Elearning/EduTech/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'', views.UserViewSet)


urlpatterns = [
    path('', views.home, name='home'),
    path('contact', views.contact, name='contact'),
    path('signup', views.sign_up, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('course/<str:slug>/', views.course, name='course'),
    path('checkout/<str:slug>/', views.checkout, name='checkout'),
    path('verify_payment', views.verify_payment, name='verify_payment'),
    path('mycourse', views.mycourse, name='mycourse'),
    path('rest_api/', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Elearning/Elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EduTech.urls')),
]

Elearning/EduTech/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
    first_name = models.CharField(max_length=100, null=True, default="")
    last_name = models.CharField(max_length=100, null=True, default="")
    email = models.CharField(max_length=100, null=True, default="")
    password = models.CharField(max_length=255, null=True, default="")
    mobile = models.BigIntegerField(null=True)
    gender = models.CharField(max_length=100, null=True, default="")
    
    def __str__(self):
        return self.first_name + " " + self.last_name
    

class Course_details(models.Model):
    course_name = models.CharField(max_length=100, null=True, default="")
    slug = models.CharField(max_length=100, null=True, default="")
    desc = models.TextField(max_length=200, null=True, default="")
    price = models.IntegerField(null=True, default=1)
    discount= models.IntegerField(null=True, default=1)
    course_image = models.ImageField(upload_to='static/images/')
    resource = models.FileField(upload_to='resources/course/')
    duration = models.TimeField()
    
    def __str__(self):
        return self.course_name
    

class Videos(models.Model):
    video_title = models.CharField(max_length=100, blank=True, null=True)
    video_id = models.CharField(max_length=100, blank=True, null=True)
    video_belong = models.ForeignKey(Course_details, on_delete=models.CASCADE, default=1)
    video_seq = models.IntegerField(null=True, blank=True)
    is_preview = models.BooleanField(default=False)
    
    def __str__(self):
        return self.video_title
    

class Course_info(models.Model):
    desc = models.CharField(max_length=100, null=True, blank=True)
    course = models.ForeignKey(Course_details, on_delete=models.CASCADE)
    
    class Meta:
        abstract = True


class tag(Course_info):
    pass


class prereq(Course_info):
    pass


class learning(Course_info):
    pass
    
    
class User_Course(models.Model):
    user = models.ForeignKey(Signup, on_delete=models.CASCADE)
    course = models.ForeignKey(Course_details, on_delete=models.CASCADE) 
    
    def __str__(self):
        return f'{self.user.first_name} - {self.course.course_name}'
    

class Payment(models.Model):
    order_id = models.CharField(max_length=200, null=True, blank=True)
    payment_id = models.CharField(max_length=200, blank=True, null=True)
    user_info = models.ForeignKey(Signup, on_delete=models.CASCADE)
    course = models.ForeignKey(Course_details, on_delete=models.CASCADE)
    course_info = models.ForeignKey(User_Course, on_delete=models.CASCADE, null=True)
    status = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.order_id
    

class Ref_code(models.Model):
    code = models.CharField(max_length=100)
    course = models.ForeignKey(Course_details, on_delete=models.CASCADE)
    discount = models.IntegerField(default=0)
    
    def __str_(self):
        return self.code
    

Elearning/EduTech/views.py
from django.shortcuts import render, HttpResponse, redirect

# Create your views here.
from .models import *
import razorpay
from django.contrib.auth.hashers import check_password, make_password
from Elearning.settings import *
from time import time
from django.views.decorators.csrf import csrf_exempt, csrf_protect


client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))


def home(request):
    
    course_dtls = Course_details.objects.all()
    context = {
        'course_dtls' : course_dtls,
    }
    
    return render(request, 'index.html', context=context)


def contact(request):
    return render(request, 'contact.html')


def sign_up(request):
    if request.method == 'POST':
        f_name = request.POST.get('fname')
        l_name = request.POST.get('lname')
        email_id = request.POST.get('email')
        password = request.POST.get('password')
        mobile_no = request.POST.get('mobile')
        gender = request.POST.get('gender')
        
        sign_obj = Signup(
            first_name = f_name,
            last_name = l_name,
            email = email_id,
            password = make_password(password),
            mobile = mobile_no,
            gender = gender,
        )
        
        sign_obj.save()
        return HttpResponse("Registration successful")

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
           email_id = Signup.objects.get(email = email)
        
           if email_id:
               if check_password(password, email_id.password):
                   request.session['name'] = email_id.first_name
                   request.session['email'] = email_id.email
                   return redirect('home')
               else:
                   return HttpResponse("wrong password")
        except:
            return HttpResponse("email does not exist")


def logout(request):
    request.session.clear()
    return redirect('home')
    
    
def course(request, slug):
    course = Course_details.objects.get(slug=slug)
    s_no = request.GET.get('serial_no')
    
    if s_no is None:
        s_no = 1
    
    try:
        video = Videos.objects.get(video_belong=course, video_seq=s_no)
        if video.is_preview is False:
            if request.session.get('name') is None:
                return redirect('home')
            
            else:
                user_id = Signup.objects.get(
                    email = request.session['email'])
                # print(user_id)
        
    except:
        return redirect('home')
    
    return render(request, 'course.html',{'video_fetch': course, 'video': video})


def checkout(request, slug):
    course = Course_details.objects.get(slug=slug)
    coupon_code = request.GET.get('coupon')
    
    
    try:
       user_id = Signup.objects.get(
                     email = request.session['email'])
    
    except:
        return redirect('home')
    
    
    payment = None
    order = None
    order_id = None
    error = None
    coup_msg = None
    coup = None
    amount = None
    if error is None:
        amount = int(course.price - (course.price * course.discount * 0.01))
        amount = amount * 100
    
    if coupon_code:
        try:
            coup = Ref_code.objects.get(code=coupon_code, course=course)
            amount = int(course.price - (course.price * coup.discount * 0.01))
            amount = amount * 100
            # coup_msg = "Successfully Applied"
            # print(coup_msg)
            # print("coupon code", "-----", amount)
            # print(amount)
        except:
            coup_msg = "Invalid Coupon Code"
    
    create_payment = request.GET.get('action')
    if create_payment == "payment":
        try:
            user_course = User_Course.objects.get(user=user_id, course=course)
            return HttpResponse("You have already purchesed this course")
        except:
            pass
        
        
        data = { 
                "amount": amount, 
                "currency": "INR", 
                "receipt": f"Elearning-{int(time())}" 
        }
        order = client.order.create(data=data) 
        
        order_id = order.get('id')
        payment = Payment()
        payment.order_id = order_id
        payment.course = course
        payment.user_info =  user_id
        payment.save()
        
    
    context = {
        'course':course,
        'pay' : 1,
        'order': order,  
        'order_id': order_id,
        'amount' : amount,
        'coupon_msg' : coup_msg,
        'coup' : coup
    }
    
    return render(request, 'checkout.html', context=context)


@csrf_exempt
def verify_payment(request):
    if request.method == "POST":
        # print(request.POST)
        data = request.POST
        client.utility.verify_payment_signature(
        # 'razorpay_order_id': razorpay_order_id,
        # 'razorpay_payment_id': razorpay_payment_id,
        # 'razorpay_signature': razorpay_signature
        data
        )
        payment = Payment.objects.get(order_id = data['razorpay_order_id'])
        payment.payment_id = data['razorpay_payment_id']
        payment.status = True
       
        
        usercourse = User_Course(user = payment.user_info, course = payment.course)
        usercourse.save()
        
        payment.course_info = usercourse
        
        payment.save()
        
    try:
        return redirect('mycourse')
    except:
        return redirect('not working')
    
    
def mycourse(request):
    user = Signup.objects.get(email=request.session['email'])
    
    user_course = User_Course.objects.filter(user=user)
    
    context = {
        'user_course' : user_course
    }
    
    return render (request, 'mycourse.html', context=context)


from .serializers import *
from rest_framework import viewsets

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Signup.objects.all()
    serializer_class = SignUpSerializer

        
    
    

Elearning/EduTech/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
        <header class="p-3 text-bg-dark">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <h2 class="me-5">EduTech</h2>
                </a>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">Home</a></li>
                  {% comment %} <li><a href="{% url 'contact' %}" class="nav-link px-2 text-white">Contact</a></li> {% endcomment %}
                  <li><a href="#" class="nav-link px-2 text-white">Courses</a></li>
                  {% if request.session.name %}
                  <li><a href="{% url "mycourse" %}" class="nav-link px-2 text-white">My Course</a></li>
                  <li><a href="#" class="nav-link px-2 text-white">FAQ's</a></li>
                  {% else %}
                  <li><a href="#" class="nav-link px-2 text-white">FAQ's</a></li>
                  {% endif %}

                  <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>
        
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                  <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                </form>
        
                <div class="text-end">
                  {% if request.session.name %}
                  <a href="{% url 'logout' %}" class="btn btn-outline-light me-2">
                    Logout
                  </a> 
                  <a href="/" class="btn btn-warning">
                    <h6 class="">{{request.session.name}}</h6>
                  </a>

                  {% else %}
                  <button type="button" class="btn btn-outline-light me-2" data-bs-toggle="modal" data-bs-target="#login">
                    Login
                  </button> 
                  <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#signup">
                    Sign up
                  </button>
                  {% endif %}
                </div>
              </div>
            </div>
          </header>
    </div>
        {% block content %}{% endblock content %}

        {% comment %} Model For SignUp {% endcomment %}
        <div class="modal fade" id="signup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Sign Up</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  
                    <form class="row g-3" action="{% url 'signup' %}" method="post">
                        {% csrf_token %}
                        <div class="col-md-6">
                          <label for="fname" class="form-label">First Name</label>
                          <input type="text" class="form-control" id="fname" name="fname">
                        </div>
                        <div class="col-md-6">
                          <label for="lname" class="form-label">Last Name</label>
                          <input type="text" class="form-control" id="lname" name="lname">
                        </div>
                        <div class="col-md-6">
                          <label for="email" class="form-label">Email</label>
                          <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="col-md-6">
                          <label for="password" class="form-label">Password</label>
                          <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <div class="col-md-6">
                          <label for="mobile" class="form-label">Mobile</label>
                          <input type="number" class="form-control" id="mobile" name="mobile">
                        </div>
                        <div class="col-md-6">
                          <label for="gender" class="form-label">Gender</label>
                          <br>
                          <input type="radio" class="form-check-input me-4" id="male" name="gender" value="male"> Male
                          <br>
                          <input type="radio" class="form-check-input me-4" id="female" name="gender" value="female"> Female
                        </div>
                        
                        <div class="col-12">
                          <button type="submit" class="btn btn-primary">Sign in</button>
                        </div>
                      </form>

                </div>
              </div>
            </div>
          </div>

        
          {% comment %} Model For Login {% endcomment %}
        <div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Login</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  
                    <form action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                          <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                          <div class="col-sm-10">
                            <input type="email" class="form-control" id="inputEmail3" name="email">
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                          <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputPassword3" name="password">
                          </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Sign in</button>
                      </form>
                </div>
              </div>
            </div>
          </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

Elearning/EduTech/templates/checkout.html
{% extends 'base.html' %}
{% load calc_discount %}
{% block content %}



<div class="container my-3 text-center">
    <div class="row mx-auto border border-primary">
        <div class="col border border-primary">
            <div class="card" style="width: 18rem;">
                <img src="{{course.course_image.url}}" class="card-img-top" alt="course image">
                <div class="card-body">
                  <p class="card-text">{{course.desc}}</p>
                </div>
              </div>
        </div>
        <div class="col border border-primary">
            <h1>
                {{course.course_name}}
            </h1>
            <div class="alert alert-info" role="alert">
                
                {% if coup %}
                Discounted Price : <h2>Rs.{% price_after_discount course.price coup.discount %} </h2>
                <a href="?action=payment&coupon={{coup.code}}" class="btn btn-success border" id="rzp-button1">Continue Payment</a>

                {% else %}
                Discounted Price : <h2>Rs.{% price_after_discount course.price course.discount %} </h2>
                <a href="?action=payment&coupon={{coup.code}}" class="btn btn-success border" id="rzp-button1">Continue Payment</a>
                {% endif %}
            </div>
        
               <form class="row g-3">
                <h3>Coupon Code:</h3>
                 {% if coupon_msg %}
                  <div class="alert alert-danger" role="alert">
                 {{coupon_msg}}!
                  </div>
                  {% elif coup %}
                  <div class="alert alert-success" role="alert">
                   You got {{coup.discount}}% Discount
                     </div>
                 {% endif %}
                <div class="col-md-8 ms-2">
                    <input type="text" class="form-control" name="coupon" placeholder="Enter Coupon Code">
                </div>

                <div class="col-md-3">
                    <input type="submit" class="btn btn-primary" value="Apply Coupon">
                </div>
               </form>
               <br>
              {% comment %} <a href="?action=payment" class="btn btn-primary mb-3 mt-3" id="rzp-button1">Buy Now</a> {% endcomment %}
        </div>
    </div>
</div>

{% if order is not None %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_2mDPgs6QLWmGrS", // Enter the Key ID generated from the Dashboard
    //"amount": "5000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise 
    "currency": "INR",
    "name": "EduTech",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "amount": "{{amount}}",
    "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "http://localhost:8000/verify_payment",
    "prefill": {
        "name": "{{user.first_name}}",
        "email": "{{user.email}}",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);

rzp1.open();

</script>
{% endif %}

{% if error is not None %}
<script>
    alert('{{error}}')
</script>
{% endif %}

{% endblock content %}

Elearning/EduTech/templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact
{% endblock title %}

{% block content %}
<h1> This is my Contact Page</h1>
{% endblock content %}

Elearning/EduTech/templates/course.html
{% extends 'base.html' %}

{% block title %}
Course
{% endblock title %}

{% load calc_discount %}

{% block content %}
<style>
  .curse{
    cursor: not-allowed;
  }
</style>

<div class="container my-3">
    <div class="row">
        
        <div class="col-2">
            <ul class="list-group">
              {% is_enroll request video_fetch as enrolled %}
                {% for video_title in video_fetch.videos_set.all %}
                <li class="list-group-item {% if video_title == video %}active-video{% endif %}" aria-current="true">
                    <a {% if not enrolled and not video_title.is_preview %} href="../../checkout/{{video_fetch.slug}}" {% else %} href="?serial_no={{video_title.video_seq}}" {% endif %} class="{% if video_title == video %}active-video-link{% endif %} {% if not enrolled and not video_title.is_preview %}text-muted curse{% endif %}">{{video_title}}</a>
                </li>
                {% endfor %}
              </ul>
        </div>
         
        {% comment %} {% for vid in video %} {% endcomment %}
        <div class="col-10">
            <iframe width="100%" height="480" src="https://www.youtube.com/embed/{{video.video_id}}" title="Introduction to Python (Hindi) | What is Python? full Explanation" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        {% comment %} {% endfor %} {% endcomment %}
    </div>
    <div class="container">
        <div class="row">
            <h1>Tags</h1>
            <hr>
            {% for tag in video_fetch.tag_set.all %}
              <div class="col-12">
                {{tag.desc}} 
              </div>
            {% endfor %}
        </div>
        <div class="row">
            <h1>Learning</h1>
            <hr>
            {% for tag in video_fetch.learning_set.all %}
              <div class="col-12">
                {{tag.desc}} 
              </div>
            {% endfor %}
        </div>
        <div class="row">
            <h1>Pre Req.</h1>
            <hr>
            {% for tag in video_fetch.prereq_set.all %}
              <div class="col-12">
                {{tag.desc}} 
              </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

Elearning/EduTech/templates/index.html
{% extends 'base.html' %}

{% load calc_discount %}

{% block title %}
EduTech
{% endblock title %}

{% block content %}

<div class="container my-3">
    
    <div class="row text-center">
        {% for crs_dtls in course_dtls %}
        <div class="col-4 text-center my-3">
            <div class="card" style="width: 18rem;">
                <img src="{{crs_dtls.course_image.url}}" class="card-img-top" alt="{{crs_dtls.course_image.url}}" height=150>
                <div class="card-body">
                  <h3 class="card-title">{{crs_dtls.course_name}}</h3>
                  <p class="card-text">{{crs_dtls.desc}}</p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Course Price: <strong>Rs. <strike>{{crs_dtls.price}}</strike></strong></li>
                  <li class="list-group-item">Discount: {{crs_dtls.discount}}%</li>
                  <li class="list-group-item">You Pay: <strong> Rs.{% price_after_discount crs_dtls.price crs_dtls.discount %} </strong></li>
                </ul>
                <div class="card-body text-center">
                  {% is_enroll request crs_dtls as enrolled %}
                  {% if enrolled %}
                  <a href="course/{{crs_dtls.slug}}/" {% if not request.session.name %}data-bs-toggle="modal" data-bs-target="#login"{% endif %}class="card-link btn btn-primary">Enrolled</a>
                  {% else %}
                  <a href="checkout/{{crs_dtls.slug}}/" {% if not request.session.name %}data-bs-toggle="modal" data-bs-target="#login"{% endif %}class="card-link btn btn-primary">Enroll</a>
                  <a href="course/{{crs_dtls.slug}}/" class="card-link btn btn-primary">More</a>
                  {% endif %}
                </div>
              </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock content %}

Elearning/EduTech/templates/mycourse.html
{% extends "base.html" %}

{% block title %}
My Course
{% endblock title %}

{% block content %}
<div class="container">
    <p class="display-6">My Courses</p>
    <hr>
    <div class="row">
        {% for uc in user_course %}

        <div class="col">
            <div class="card max-auto" style="width: 18rem;">
                <img src="{{uc.course.course_image.url}}" alt="loading..." class="card-img-top" height="200">
                <div class="card-body">
                    <h5 class="card-title">{{uc.course.course_name}}</h5>
                    <p class="card-title">{{uc.course.desc}}</p>
                </div>
                <div class="card-footer p-3">
                    <div class="row no-gutters">
                        <div class="col border-right text-center">
                            <a href="course/{{uc.course.slug}}" class="btn btn-primary btn-block mystyle"> Start Course </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>    

{% endblock content %}